version: '3'

services:
  mysqldb:
    image: mysql:8.0.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d